### ISSUE TITLE
README : Wie aktualisiere ich im AddOn den Vendor

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/for_sa11y#13]
**Feature description / Feature Beschreibung**

Eine kleine Beschreibung wäre gut. Hätte sonst bereits einen PR für [3.0.7](https://github.com/ryersondmp/sa11y/releases/tag/3.0.7) eingereicht.

**Comment by skerbis** [comment]
Danke für die Info. Steht nun in der Readme
