### ISSUE TITLE
Deployment funktioniert nicht initial, man muss es live re-installieren

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/for_sa11y#35]
**Description / Beschreibung**

Wir arbeiten ja lokal und deployen dann auf die Server.
Sa11y macht hier Probleme, sodass man immer das AddOn Live re-installieren muss.

Im Frontend erscheint das hier

<img width="981" alt="Bildschirmfoto 2024-08-20 um 14 51 16" src="https://github.com/user-attachments/assets/404a02c1-069d-4e2f-a1aa-1e28c4870d71">

**Comment by skerbis** [comment]
Hmmm ... da JS scheint ja geladen zu werden, sonst bekämst du die Meldung ja nicht. 
Steht denn irgendwas in der Console?

**Comment by tbaddade** [comment]
Die hier genutzte Version ist die `4.2.2`

Hatte das aber auch schon in anderen Projekten, nur eben noch nie gemeldet.

**Comment by skerbis** [comment]
bitte auf 4.2.3 updaten, da war noch n Bug schätze aber das wird es nicht sein. 
Wird die default_config aus der package.yml evtl. nicht gesetzt?

**Comment by skerbis** [comment]
@tbaddade 

```root: 'body'```
Aus der package.yml scheint nicht beachtet zu werden oder ist leer. 



```
Fehler
Leider liegt ein Problem mit der Barrierefreiheitsprüfung auf dieser Seite vor. Können Sie es bitte über dieses Formular (Öffnet neuen Tab) oder auf GitHub (Öffnet neuen Tab) melden?

querySelector@[native code] @/assets/addons/for_sa11y/vendor/sa11y/dist/js/sa11y.umd.min.js:12:143293 

```

**Comment by tbaddade** [comment]
> Wird die default_config aus der package.yml evtl. nicht gesetzt?

Das ist der Grund. Der Namespace müsste aktiv sein, wenn die Config-Werte gesynct werden sollen.
Ist aber mehr ein Thema für YDeploy oder des Entwicklers.

**Comment by tbaddade** [comment]
@skerbis Falls du es für sinnvoll hältst, dass die config-Werte syncen, dann müsste du hier Sa11y ergänzen.
https://github.com/yakamara/ydeploy/blob/main/package.yml#L26-L32

**Comment by skerbis** [comment]
habe es nun so gelöst: https://github.com/FriendsOfREDAXO/for_sa11y/blob/e9bb7fcb707cee18543bdd657e4b8dd17aaae7ff/lib/for_sa11y.php#L20

**Comment by skerbis** [comment]
hoffe das passt
